### ISSUE TITLE
Two scrollbars visible at all times

### ISSUE THREAD

**Issue by hrhr-77** [kfigiela/saffire-mixer-ui#2]
Two scrollbars visible at all times, no matter what size of the window is:

![image](https://user-images.githubusercontent.com/30800496/80375943-5ecba680-8899-11ea-91f9-04a0ea8f14c9.png)

Saffire LE Mixer v1.0.0
OS: MacOS Catalina 10.15.3

**Comment by kfigiela** [comment]
Thanks for reporting this. Do you have external mice connected or configured macOS to always display scrollbars?

**Comment by hrhr-77** [comment]
Sorry for late response, I didn't get any notification from GitHub.

Yes, I'm using USB mouse connected to a Mac Mini. I've checked system settings and switching "Show scroll bars" to "When scrolling" fixes the issue.
When "Automatically based on mouse or trackpack" or "Always" is selected, the scrollbars reappear.

**Comment by kfigiela** [comment]
Thanks for the information! I'll try to fix this when time permits :)

**Comment by kfigiela** [comment]
I've addressed this in c9d5988d2f41c58d9298d3ee8175b019bdbc408f. I've also issued bugfix release https://github.com/kfigiela/saffire-mixer-ui/releases/tag/v1.0.1.

**Comment by hrhr-77** [comment]
I confirm, 1.0.1 works perfectly on Catalina 10.15.5. Thank you!
